# Generated by Django 6.0.7 on 2026-07-09 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatoCurioso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('imagen', models.CharField(help_text='Nombre de archivo dentro de /static/images/datos/ (ej. leyenda.jpg)', max_length=255)),
                ('texto', models.TextField()),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Dato curioso',
                'verbose_name_plural': 'Datos curiosos',
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Fauna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('imagen', models.CharField(help_text='Nombre de archivo dentro de /static/images/fauna/ (ej. oso_andino.jpg)', max_length=255)),
                ('descripcion', models.TextField()),
                ('habitat', models.TextField(blank=True)),
                ('alimentacion', models.TextField(blank=True)),
                ('estado_conservacion', models.CharField(blank=True, max_length=100)),
                ('curiosidades', models.TextField(blank=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Fauna',
                'verbose_name_plural': 'Fauna',
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Flora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('nombre_cientifico', models.CharField(blank=True, max_length=150)),
                ('imagen', models.CharField(help_text='Nombre de archivo dentro de /static/images/flora/ (ej. orquidea.jpg)', max_length=255)),
                ('descripcion', models.TextField()),
                ('importancia_ecologica', models.TextField(blank=True)),
                ('curiosidades', models.TextField(blank=True)),
                ('modelo_3d', models.CharField(blank=True, help_text='Opcional. Ruta relativa dentro de /static/ a un modelo .glb/.gltf.', max_length=255)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Flora',
                'verbose_name_plural': 'Flora',
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Historia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=150)),
                ('imagen', models.CharField(help_text='Nombre de archivo dentro de /static/images/historia/ (ej. fundacion.jpg)', max_length=255)),
                ('fecha', models.CharField(blank=True, help_text="Ej. '1534' o 'Época preincaica'", max_length=100)),
                ('descripcion', models.TextField()),
                ('dato_curioso', models.TextField(blank=True)),
                ('codigo_qr', models.CharField(blank=True, help_text='Opcional. Ruta relativa dentro de /static/ a una imagen de código QR.', max_length=255)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Historia',
                'verbose_name_plural': 'Historia',
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Lugar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_proyecto', models.CharField(default='Turismo Inmersivo de las Ruinas de Malqui Machay', max_length=150)),
                ('subtitulo', models.CharField(default='La Maná, Cotopaxi · Recorrido Virtual Inmersivo', max_length=200)),
                ('introduccion', models.TextField(default='Explora de forma inmersiva las Ruinas de Malqui Machay: su flora, su fauna, su historia y sus tradiciones, en un recorrido virtual compatible con Meta Quest.')),
                ('logo_proyecto', models.CharField(blank=True, help_text='Ruta relativa dentro de /static/ (ej. showroom/images/logo_proyecto.png)', max_length=255)),
                ('logo_utc', models.CharField(blank=True, help_text='Ruta relativa dentro de /static/ (ej. showroom/images/logo_utc.png)', max_length=255)),
                ('imagen_panoramica', models.CharField(default='showroom/images/panoramica_malqui.jpg', help_text='Imagen panorámica de fondo mostrada en la pantalla de bienvenida.', max_length=255)),
                ('audio_ambiental', models.CharField(default='audio/bosque.mp3', help_text='Ruta relativa dentro de /static/ al audio ambiental de bosque/aves/agua.', max_length=255)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Lugar (información general)',
                'verbose_name_plural': 'Lugar (información general)',
            },
        ),
        migrations.CreateModel(
            name='Modelo3D',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Maqueta de Malqui Machay', max_length=150)),
                ('descripcion', models.TextField(blank=True)),
                ('archivo_glb', models.CharField(default='models/malqui.glb', help_text='Ruta relativa dentro de /static/ (ej. models/malqui.glb)', max_length=255)),
                ('escala', models.FloatField(default=1.0)),
                ('velocidad_rotacion', models.FloatField(default=8.0, help_text='Segundos que tarda en dar una vuelta completa (rotación lenta).')),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Modelo 3D',
                'verbose_name_plural': 'Modelos 3D',
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PuntoTuristico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('descripcion', models.TextField()),
                ('imagen', models.CharField(blank=True, help_text='Ruta relativa dentro de /static/ (ej. showroom/images/mirador.jpg)', max_length=255)),
                ('pos_x', models.FloatField(default=0.0)),
                ('pos_y', models.FloatField(default=1.6)),
                ('pos_z', models.FloatField(default=-5.0)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Punto turístico',
                'verbose_name_plural': 'Puntos turísticos',
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Ruinas de Malqui Machay', max_length=150)),
                ('descripcion', models.TextField(blank=True)),
                ('archivo', models.CharField(default='videos/malqui.mp4', help_text='Ruta relativa dentro de /static/ (ej. videos/malqui.mp4)', max_length=255)),
                ('miniatura', models.CharField(blank=True, help_text='Opcional. Imagen de previsualización (poster) del video.', max_length=255)),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videos',
                'ordering': ['orden', 'id'],
            },
        ),
    ]
